on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_run:
    runs-on: ubuntu-24.04
    steps:
      - run: touch build.tar.xz
      - run: echo "----- upload artifact -----"
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build.tar.xz
          if-no-files-found: error

  tag_and_push_artifact:
    needs: build_and_run
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.WORKFLOW_RELEASE_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - run: echo "----- download artifact ------"
      - uses: actions/download-artifact@v4
        with:
          name: build

      - run: echo "----- rename artifacts ------"
      - run: echo $(basename ${{github.ref}}) > branch
      - run: echo $(git rev-parse --short=7 HEAD) > version
      - run: mv build.tar.xz $(cat branch)-$(cat version).tar.xz

      - run: echo "----- tag build -----"
      - run: git tag $(cat branch)-$(cat version) && git push --tags

      - run: echo "----- push artifacts to "build" release -----"
      - run: gh release upload --clobber build $(cat branch)-$(cat version).tar.xz

